#!/usr/bin/python

import urllib, urllib2, json, sys


def kwic2str(kwic):
    out = ""
    for s in kwic:
        if "coll" in s["class"]:
            out += "<h>%s</h>" % s["str"]
        elif not s["class"]:
            out += s["str"]
    return out.encode("utf-8")


base_url = 'https://api.sketchengine.co.uk/corpus/'
method = 'view'

corp = sys.argv[1]
usr = sys.argv[2]
apikey = sys.argv[3]


attrs = dict(corpname=corp, format='json', api_key=apikey,
             change_gdex=False, viewmode="sen")

def get_examples (cql):
    attrs['q'] = ["q" + cql, "e200"]

    encoded_attrs = urllib.quote(json.dumps(attrs))
    url = base_url + method + '?username=%s;json=%s' % (usr, encoded_attrs)

    request = urllib2.Request(url)

    file = urllib2.urlopen(request)
    data = file.read()
    file.close()

    data = json.loads(data)
    examples = []
    if 'Lines' in data:
        for l in data["Lines"]:
            examples.append(kwic2str (l["Left"]) + kwic2str (l["Kwic"]) + kwic2str (l["Right"]))
    return examples

for h in sys.stdin:
    entry = json.loads(h)
    if "senses" in entry:
        for s in entry["senses"]:
            s["examples"] = get_examples(s["conclink"])
    else:
        conclink = entry.get('conclink', '')
        entry["examples"] = conclink and get_examples(conclink) or []
    print json.dumps(entry)
